@startuml sequence
title sequence

actor 利用者

participant EngineerView
participant EngineerManager
participant Engineer
database CSV

/'社員情報をCSVファイルから読み込む'/
/' ？？
利用者 -> EngineerView : データフォルダを作成
EngineerView -> CSV : loadEmgineer()
alt ファイルあり
CSV --> EngineerView : 社員情報を読み込む
EngineerView --> 利用者 : 社員情報取得
else ファイルなし
EngineerManager --> CSV : createNewFile()
end
'/

/'社員情報を追加する'/
利用者 -> EngineerView : 追加ボタン押下
EngineerView -> EngineerManager : Engineer(入力情報)
EngineerManager -> Engineer : addEngineer()
EngineerManager -> CSV : saveEmgineer()
CSV --> EngineerManager : 保存成功
EngineerManager --> EngineerView : 追加完了
EngineerView --> 利用者 : logger.info()

/'社員情報を削除する'/
利用者 -> EngineerView : 削除ボタン押下
EngineerView -> EngineerManager : Engineer(入力情報)
EngineerManager -> Engineer : removeEngineer()
EngineerManager -> CSV : saveEmployees()
CSV --> EngineerManager : 削除成功
EngineerManager --> EngineerView : 削除完了
EngineerView --> 利用者 : logger.info()

/'社員情報のリストを取得する'/
利用者 -> EngineerView : 社員を選択
EngineerView -> EngineerManager : getEngineer()
EngineerManager --> EngineerView : 社員情報のリストを取得(一括、選択)
EngineerView --> 利用者 : 社員情報のリストを表示

@enduml