@startuml state_diagram
title state_diagram

[*] --> 一覧表示中

一覧表示中 --> 新規登録中 : 新規追加
新規登録中 --> 一覧表示中 : 登録完了

一覧表示中 --> 詳細表示中 : エンジニア選択
詳細表示中 --> 編集中 : 編集ボタン
編集中 --> 一覧表示中 : 保存完了

一覧表示中 --> 削除確認中 : 削除ボタン
削除確認中 --> 一覧表示中 : 削除完了
削除確認中 --> 一覧表示中 : キャンセル

@enduml